# Tratamento e análise de dados com Pandas

In [18]:
import pandas as pd

In [19]:
dados = pd.read_csv("name_gender_dataset.csv")

## Descrição dos dados

In [20]:
dados.head()

      Name Gender    Count  Probability
0    James      M  5304407     0.014517
1     John      M  5260831     0.014398
2   Robert      M  4970386     0.013603
3  Michael      M  4579950     0.012534
4  William      M  4226608     0.011567

In [21]:
dados.shape

(147269, 4)

In [22]:
dados.dtypes

Name               str
Gender             str
Count            int64
Probability    float64
dtype: object

In [23]:
dados.isnull().sum()

Name           0
Gender         0
Count          0
Probability    0
dtype: int64

In [24]:
dados.nunique()

Name           133910
Gender              2
Count            7659
Probability      7659
dtype: int64

## Tratamento da qualidade dos dados

Não foram encontrados valores nulos no dataset. Também não foram encontradas colunas com valores constantes. Portanto, não foi necessário remover dados nesta etapa.

## Perguntas sobre o dataset

### 1. Quantos registros há para cada gênero?

In [25]:
dados["Gender"].value_counts()

Gender
F    89749
M    57520
Name: count, dtype: int64

### 2. Quais são os registros do gênero feminino?

In [26]:
dados[dados["Gender"] == "F"]

             Name Gender    Count   Probability
5            Mary      F  4169663  1.141129e-02
14      Elizabeth      F  1704140  4.663789e-03
15       Patricia      F  1608260  4.401391e-03
16       Jennifer      F  1584426  4.336163e-03
19          Linda      F  1480592  4.051996e-03
...           ...    ...      ...           ...
133945      Zyika      F        1  2.736740e-09
133946   Zymeliah      F        1  2.736740e-09
133947     Zyrije      F        1  2.736740e-09
133948    Zyrinah      F        1  2.736740e-09
133949       Zyta      F        1  2.736740e-09

[89749 rows x 4 columns]

### 3. Quais são os registros do gênero masculino?

In [27]:
dados[dados["Gender"] == "M"]

           Name Gender    Count   Probability
0         James      M  5304407  1.451679e-02
1          John      M  5260831  1.439753e-02
2        Robert      M  4970386  1.360266e-02
3       Michael      M  4579950  1.253414e-02
4       William      M  4226608  1.156713e-02
...         ...    ...      ...           ...
147264   Zylenn      M        1  2.736740e-09
147265   Zymeon      M        1  2.736740e-09
147266   Zyndel      M        1  2.736740e-09
147267   Zyshan      M        1  2.736740e-09
147268    Zyton      M        1  2.736740e-09

[57520 rows x 4 columns]

### 4. Qual é a média da quantidade (Count)?

In [28]:
dados["Count"].mean()

np.float64(2481.1613442068597)

### 5. Qual é o nome com a maior quantidade de ocorrências?

In [29]:
dados.sort_values("Count", ascending=False).head(1)

    Name Gender    Count  Probability
0  James      M  5304407     0.014517

### 6. Quais são os 10 nomes da categoria F com mais ocorrências?

In [30]:
dados[dados["Gender"] == "F"].sort_values("Count", ascending=False).head(10)

         Name Gender    Count  Probability
5        Mary      F  4169663     0.011411
14  Elizabeth      F  1704140     0.004664
15   Patricia      F  1608260     0.004401
16   Jennifer      F  1584426     0.004336
19      Linda      F  1480592     0.004052
20    Barbara      F  1459870     0.003995
29   Margaret      F  1280255     0.003504
32    Jessica      F  1173979     0.003213
33      Sarah      F  1162143     0.003180
34      Susan      F  1154677     0.003160

### 7. Qual é a média de ocorrências dos nomes da categoria F?

In [31]:
dados[dados["Gender"] == "F"]["Count"].mean()

np.float64(2012.5361173940657)

### 8. Quais são os 10 nomes da categoria M com mais ocorrências?

In [32]:
dados[dados["Gender"] == "M"].sort_values("Count", ascending=False).head(10)

       Name Gender    Count  Probability
0     James      M  5304407     0.014517
1      John      M  5260831     0.014398
2    Robert      M  4970386     0.013603
3   Michael      M  4579950     0.012534
4   William      M  4226608     0.011567
6     David      M  3787547     0.010366
7    Joseph      M  2695970     0.007378
8   Richard      M  2638187     0.007220
9   Charles      M  2433540     0.006660
10   Thomas      M  2381034     0.006516

### 9. Qual é o percentual de registros de cada categoria?

In [33]:
dados["Gender"].value_counts(normalize=True) * 100

Gender
F    60.942221
M    39.057779
Name: proportion, dtype: float64

### 10. Quantos registros possuem mais de 100.000 ocorrências em cada categoria?

In [34]:
dados[dados["Count"] > 100000]["Gender"].value_counts()

Gender
F    365
M    299
Name: count, dtype: int64